version: "3.9"
services:
  frontend:
    image: swat-frontend
    build: ./src/frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - swat-app
    volumes:
      - ./src/frontend:/usr/src/app
  issueService:
    image: swat-issue-api
    build: ./src/issueService/
    ports:
      - "8080:8080"
    networks:
      - swat-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2-bionic
    ports:
      - "8000:8000"
    networks:
      - swat-app
    volumes:
      - mongo-data:/data/db
networks:
  swat-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local